/**
 * Session bookkeeping: maps the stable **client** session ids (exposed in CDT
 * URLs and to all extension code) onto the **host** session ids assigned by
 * the app in `Plugin/load` / `Plugin/runScript` replies.
 *
 * Client ids are generated by us and globally unique across apps; the
 * indirection lets a future reload-fallback re-bind a client id to a new host
 * id without any consumer noticing (ARCHITECTURE.md §5.4).
 */

import { foldPathCase } from "../pathCase";
import type { AppInfo } from "../protocol/types";

export type SessionKind = "plugin" | "script";

export interface PluginSession {
    /** Stable id exposed to the extension and embedded in CDT URLs. */
    readonly clientSessionId: string;
    /** Current id in the host app's session space. */
    hostSessionId: string;
    readonly kind: SessionKind;
    /** `manifest.id`, or `"__uxpScript:<fileName>"` for script pseudo-sessions. */
    readonly pluginId: string;
    /** Display name (manifest name or script file name). */
    readonly name: string;
    /** Absolute plugin folder / script folder path. */
    readonly pluginPath: string;
    /** Absolute path of `manifest.json` (plugin sessions only). */
    readonly manifestPath?: string;
    /**
   * Absolute path of the original script file as registered in the panel
   * (script sessions only). Differs from `pluginPath`/`name` when the script
   * was run from a generated temp file (e.g. `.ts` type-stripping) — use this
   * to match a session back to its registry entry.
   */
    readonly scriptSourcePath?: string;
    /** The app the session lives in. */
    readonly app: AppInfo;
    /** Broker-assigned id of the owning app connection. */
    readonly appConnectionId: number;
}

export class SessionRegistry {
    private nextClientId = 1;
    private readonly byClientId_ = new Map<string, PluginSession>();

    add(input: Omit<PluginSession, "clientSessionId">): PluginSession {
        const session: PluginSession = {
            ...input,
            clientSessionId: `uxp-session-${String(this.nextClientId++)}`,
        };
        this.byClientId_.set(session.clientSessionId, session);
        return session;
    }

    byClientId(clientSessionId: string): PluginSession | undefined {
        return this.byClientId_.get(clientSessionId);
    }

    byHostId(appConnectionId: number, hostSessionId: string): PluginSession | undefined {
        for (const session of this.byClientId_.values()) {
            if (
                session.appConnectionId === appConnectionId
                && session.hostSessionId === hostSessionId
            ) {
                return session;
            }
        }
        return undefined;
    }

    /** All live sessions (snapshot). */
    list(): PluginSession[] {
        return [...this.byClientId_.values()];
    }

    /** Live sessions belonging to a given manifest file. */
    forManifest(manifestPath: string): PluginSession[] {
        const key = foldPathCase(manifestPath);
        return this.list().filter(
            (s) => s.manifestPath !== undefined && foldPathCase(s.manifestPath) === key,
        );
    }

    /** Remove one session. Returns it when it existed. */
    remove(clientSessionId: string): PluginSession | undefined {
        const session = this.byClientId_.get(clientSessionId);
        if (session) {
            this.byClientId_.delete(clientSessionId);
        }
        return session;
    }

    /** Remove and return every session owned by an app connection (app disconnect). */
    removeAllForApp(appConnectionId: number): PluginSession[] {
        const removed = this.list().filter((s) => s.appConnectionId === appConnectionId);
        for (const session of removed) {
            this.byClientId_.delete(session.clientSessionId);
        }
        return removed;
    }
}
