import * as fs from "fs";
import * as path from "path";
import * as vscode from "vscode";
import {UxpTarget} from "../types";

// ---------------------------------------------------------------------------
// .uxprc discovery
// ---------------------------------------------------------------------------

/**
 * UDT (UXP Developer Tools) service port — used for the relay WebSocket.
 */
const UDT_PORT = 14001;

/**
 * Discover UXP plugin targets via the `.uxprc` file next to manifest.json.
 *
 * The `.uxprc` file is generated by `uxp plugin load` (devtools-cli) and
 * stores the plugin session ID assigned by the host app through the UDT Service.
 * Returns WebSocket URLs pointing to the UDT relay:
 *   ws://127.0.0.1:14001/socket/cdt/<pluginSessionId>
 */
export function discoverViaUxpRc(
  manifestDir: string,
  log: vscode.OutputChannel
): UxpTarget[] {
  const rcPath = path.join(manifestDir, ".uxprc");
  try {
    if (!fs.existsSync(rcPath)) {
      log.appendLine(`  .uxprc: not found at ${rcPath}`);
      return [];
    }

    const content = fs.readFileSync(rcPath, "utf-8");
    const rc = JSON.parse(content);
    const plugin = rc?.plugin;

    if (!plugin || !Array.isArray(plugin.sessions) || plugin.sessions.length === 0) {
      log.appendLine("  .uxprc: no plugin sessions found");
      return [];
    }

    const pluginName = plugin.info?.name || plugin.info?.id || "UXP Plugin";
    const targets: UxpTarget[] = [];

    for (const session of plugin.sessions) {
      const sessionId = session?.pluginSessionId;
      const app = session?.app;
      if (typeof sessionId !== "string" || !app) {
        continue;
      }

      const appId: string = app.id ?? "unknown";
      const appVersion: string = app.version ?? "";
      const hostApp = appId === "PS" ? "Photoshop" : appId;
      const wsUrl = `ws://127.0.0.1:${UDT_PORT}/socket/cdt/${sessionId}`;

      targets.push({
        label: `${pluginName} (${appId} ${appVersion}) [via UDT Service]`,
        hostApp,
        pluginId: sessionId,
        webSocketUrl: wsUrl,
      });

      log.appendLine(
        `  .uxprc: session "${sessionId}" for ${appId} ${appVersion} → ${wsUrl}`
      );
    }

    log.appendLine(`  .uxprc: found ${targets.length} session target(s)`);
    return targets;
  } catch (err) {
    log.appendLine(
      `  .uxprc: failed to read – ${err instanceof Error ? err.message : err}`
    );
    return [];
  }
}
